name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab=4.1.8
  - jupyter=1.0.0
  - mlflow=1.14.1
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=23.3.1
  - pandas-profiling=3.2.0
  - pyarrow=2.0
  - numpy=1.19.5
  - pydantic=1.8.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.6
